// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUVMNMw59pR8NYqMvJ8AJTBNlPXFggr4Q',
    appId: '1:387971229931:web:9265bf37f37937b13df6ae',
    messagingSenderId: '387971229931',
    projectId: 'foodbalance-61ffc',
    authDomain: 'foodbalance-61ffc.firebaseapp.com',
    storageBucket: 'foodbalance-61ffc.firebasestorage.app',
    measurementId: 'G-TJLF43NWRG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuKrCXqzuoKvpjDcTd9z7vOodXci4xn8Q',
    appId: '1:387971229931:android:efed4a4802e917e03df6ae',
    messagingSenderId: '387971229931',
    projectId: 'foodbalance-61ffc',
    storageBucket: 'foodbalance-61ffc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAH9u2nQ-XKNwiZqH1QMtK9Cc1hCtYI21I',
    appId: '1:387971229931:ios:aa25b1c1d04428873df6ae',
    messagingSenderId: '387971229931',
    projectId: 'foodbalance-61ffc',
    storageBucket: 'foodbalance-61ffc.firebasestorage.app',
    androidClientId: '387971229931-sv5tmtkopd8rr7c5f30krfbaeu3aui5o.apps.googleusercontent.com',
    iosClientId: '387971229931-hf1tdeueiuk94a85c40fbd06t7muflbh.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodbalance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAH9u2nQ-XKNwiZqH1QMtK9Cc1hCtYI21I',
    appId: '1:387971229931:ios:aa25b1c1d04428873df6ae',
    messagingSenderId: '387971229931',
    projectId: 'foodbalance-61ffc',
    storageBucket: 'foodbalance-61ffc.firebasestorage.app',
    androidClientId: '387971229931-sv5tmtkopd8rr7c5f30krfbaeu3aui5o.apps.googleusercontent.com',
    iosClientId: '387971229931-hf1tdeueiuk94a85c40fbd06t7muflbh.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodbalance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUVMNMw59pR8NYqMvJ8AJTBNlPXFggr4Q',
    appId: '1:387971229931:web:541482862083f4cd3df6ae',
    messagingSenderId: '387971229931',
    projectId: 'foodbalance-61ffc',
    authDomain: 'foodbalance-61ffc.firebaseapp.com',
    storageBucket: 'foodbalance-61ffc.firebasestorage.app',
    measurementId: 'G-T77JKV2BZE',
  );

}